### ISSUE TITLE
compare patches

### ISSUE THREAD

**Issue by DanGrayson** [Macaulay2/frobby#1]
We have three branches containing the patches used to make frobby compile in three contexts: CoCoA-patches, Debian-patches, and Macaulay2-patches.  It would be useful to compare and combine them, to get the best way going forward, now that it's up to us to maintain frobby.

@d-torrance

**Comment by d-torrance** [comment]
Cool, I'll take a look and prepare a pull request.

**Comment by DanGrayson** [comment]
One way to do it so the branches all appear to merge is to merge all three of them simultaneously into master, without committing until the differences and conflicts are resolved.  Then the git history will indicate that they've all been considered.
